name: 'Create release for tag'

on:
  workflow_dispatch:
  
  push:
    tags:
      - '23_**'

jobs:
  auto-release:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            readme.md
